name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - run: pwd
      - run: ls

      - name: Install packages
        run: sudo apt-get update && sudo apt-get install -y valac 

      - name: Run build command
        run: make
